#jpa repository를 통한 실제로 실행되는 sql문을 직접 볼 수 있게끔
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: MySQL5InnoDBDialect
  #h2 DB 직접 접근 위한 웹 콘솔 옵션 활성화
  h2:
    console:
      enabled: true
cloud:
  aws:
    credentials:
      instance-profile: false
      access-key: AKIAXBRVNLFAPSWOQD7P
      secret-key: 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
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

aws:
  s3:
    bucket: izapkbucket